language: python
python:
  - '2.7'
services:
  - docker
script:
  - 'docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"'
  - docker build -t clux/muslrust:nightly .
  - make test
after_success:
  - docker push clux/muslrust:nightly
notifications:
  email:
    on_success: change
    on_failure: always
